name: Deploy dev
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    environment:
      name: dev
      url: https://anticversecom-dev.web.app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANTICVERSECOM_DEV }}'
          channelId: live
          projectId: anticversecom-dev
