name: Deploy production

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    environment:
      name: production
      url: "https://anticverse.com"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload to server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.PROD_SERV }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASS }}
          server-dir: ${{ secrets.PROD_PATH }}
          protocol: ftps
