name: Deploy production

on:
  push:
    branches: ["prod"]

jobs:
  deploy:
    environment:
      name: production
      url: "https://anticverse.com"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload to server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.anticverse.com
          username: ${{ secrets.FTP_PROD_USER }}
          password: ${{ secrets.FTP_PROD_PASS }}
          server-dir: ${{ secrets.FTP_PROD_PATH }}
          protocol: ftps
